# kairos database config
default: &default
  encoding: utf8
  adapter: mysql2
  port: 3306

development:
  <<: *default
  database: kairos_db
  pool: 5
  host:     localhost
  username: root
  password: root


staging:
  <<: *default
  database: kairos_supmanagement
  pool: 5
  host:     172.31.17.28
  username: ged_ro@172.31.11.31
  password: rt_B6hRV9zZMm?FW

production:
  <<: *default
  database: kairos_supmanagement
  pool: 5
  host:     172.31.17.28
  username: ged_ro@172.31.11.31
  password: rt_B6hRV9zZMm?FW


