# kairos database config
default: &default
  encoding: utf8
  adapter: mysql2
  port: 3306

development:
  <<: *default
  database: kairos_db
  pool: 5
  host:     localhost
  username: root
  password: root


staging:
  <<: *default
  database: kairos_supmanagement
  pool: 5
  host:     "ec2-3-22-132-0.us-east-2.compute.amazonaws.com"
  username: ged
  password: Sgtdh+-456é+hbbfnd+

production:
  <<: *default
  database: kairos_supmanagement
  pool: 5
  host:     "ec2-3-22-132-0.us-east-2.compute.amazonaws.com"
  username: ged
  password: Sgtdh+-456é+hbbfnd+


